### ISSUE TITLE
真似して作ってみました！

### ISSUE THREAD

**Issue by ANTON072** [FiNGAHOLiC/jquery.scenemanager#2]
オブサーバ風なかんじで。
https://github.com/ANTON072/ScrollHitEvent.js

**Comment by FiNGAHOLiC** [comment]
きれいなソースで自分のよりいい気がします！
1点きになったのはリサイズ時にウインドウグリグリして基準点がwaypointを突破しても発火しないようです。

**Comment by ANTON072** [comment]
お、ありがとうございます！
